Update video2audio.yml

diff --git a/.github/workflows/video2audio.yml b/.github/workflows/video2audio.yml
--- a/.github/workflows/video2audio.yml
+++ b/.github/workflows/video2audio.yml
@@ -25,20 +25,20 @@ jobs:
 
       - name: Download file
         run: |
-          wget -O input_video.mp4 https://github.com/334456777/ffcut/releases/download/1.1.1/video.mp4 
+          wget -O input_video.mkv https://github.com/334456777/ffcut/releases/download/1.1.1/video.mkv 
 
       - name: Check if input file exists
         run: |
-          if [ ! -f "input_video.mp4" ]; then echo "Input file not found"; exit 1; fi
+          if [ ! -f "input_video.mkv" ]; then echo "Input file not found"; exit 1; fi
 
       - name: Run video processing script
         run: |
-          ffmpeg -i input_video.mp4 -vn -acodec copy output_audio.mp4
+          ffmpeg -i input_video.mkv -vn -acodec libmp3lame -q:a 2 output_audio.mp3
 
       - name: Check if output file exists
         run: |
-          if [ ! -f "output_audio.mp4" ]; then echo "Output file not found"; exit 1; fi
+          if [ ! -f "output_audio.mp3" ]; then echo "Output file not found"; exit 1; fi
 
       - name: Upload file to S3
         run: |
-          aws s3 cp ./output_audio.mp4 s3://${{ secrets.S3_BUCKET_NAME }}/audio.mp4 --acl bucket-owner-full-control
+          aws s3 cp ./output_audio.mp3 s3://${{ secrets.S3_BUCKET_NAME }}/audio.mp3
